### ISSUE TITLE
Drop of performance since Gradio update

### ISSUE THREAD

**Issue by Senooy** [C0untFloyd/roop-unleashed#103]
**Describe the bug**
I can see a clear drop of performance since the gradio update. My GPU (RTX 3070ti) is hitting 100% but it takes a much longer time to process.
Any ways to downgrade my version ?

Thanks

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?**

Latest

**Screenshots**

**Comment by eniora** [comment]
Since you have 8GB VRAM, set "Max. Number of Threads" to 5 or 6 in UI settings, apply and completely restart roop. Should fix the issue.

**Comment by eniora** [comment]
IDK man, tested earlier today on 8GB card and it was fine (after the latest update from yesterday, it significantly improved the performance for me), I could do multiple swaps and no slowdowns at all. However there was a discussion I started 2 days ago about this very same issue here: https://github.com/C0untFloyd/roop-unleashed/issues/89 C0untFloyd made an update that improved the performance.

Count also said in the future he may implement a feature to unload the models to CPU which should be beneficial for low VRAM GPUs. roop is and has always been VRAM hungry. Coincidentally I was reading the official roop discord server today and there was a small discussion about this very problem, latest roop (main and the gradio beta one) doesn't release the memory at all, unleashed is still better at it with the latest commit from yesterday regarding the VRAM usage.

**Comment by Darknessssenkrad** [comment]
same here I was able to run 1 Thread Cuda (3050 4gb vram) and I was getting 7-8 it/s now I hardly get 1-1.5 it/s and a freshresintall didn't help if I try to use more Threads I get OOM errors

**Comment by faiqraedaya** [comment]
Same issue. RTX 3070, went from XX fps to 0.0X fps. ~100% GPU and VRAM utilisation. Tinkering with the settings doesn't seem to change anything.

**Comment by eniora** [comment]
As a test, can you guys try with **tensorrt** provider in settings? set it, apply settings with 4 threads and restart roop completely. tensorrt uses less VRAM with almost same speed as cuda but it doesn't support the enhancers from what I tried. So try without any enhancer and see if you can get good FPS.

**Comment by domunix** [comment]
having the same problem, used to take 30 seconds/a minute max to process a 10 second gif, now it's taking 30 seconds/a minute per frame

**Comment by C0untFloyd** [comment]
Rewrote the chained threading last night and separated it in parts with buffered reading/writing, speeding it up about 4 times. I think it's even faster than the previous v2.0.3!
As a test video I'm using a 90 frames clip from the TV News, it's 1920x1080 resolution.

Pure swapping on my not state-of-the-art NVIDIA 2060 Super:

Processing: 100%|███████████████████████████████████████████████████████████████████████| 90/90 [00:21<00:00,  4.17frame/s, memory_usage=12.33GB, execution_threads=8]

Previously 1.4frame/s

With GFPGAN on:
Processing: 100%|███████████████████████████████████████████████████████████████████████| 90/90 [03:11<00:00,  2.13s/frame, memory_usage=13.30GB, execution_threads=8]

**Still twice as fast as previously without **enhancement!**

I need to do some more tweaking and will commit this after my regular work day.

**Comment by Siraj-HM** [comment]
> Rewrote the chained threading last night and separated it in parts with buffered reading/writing, speeding it up about 4 times. I think it's even faster than the previous v2.0.3! As a test video I'm using a 90 frames clip from the TV News, it's 1920x1080 resolution.
> 
> Pure swapping on my not state-of-the-art NVIDIA 2060 Super:
> 
> Processing: 100%|███████████████████████████████████████████████████████████████████████| 90/90 [00:21<00:00, 4.17frame/s, memory_usage=12.33GB, execution_threads=8]
> 
> Previously 1.4frame/s
> 
> With GFPGAN on: Processing: 100%|███████████████████████████████████████████████████████████████████████| 90/90 [03:11<00:00, 2.13s/frame, memory_usage=13.30GB, execution_threads=8]
> 
> **Still twice as fast as previously without enhancement!**
> 
> I need to do some more tweaking and will commit this after my regular work day.

Thank you will give it a try and let you know

**Comment by lysxelapsed** [comment]
Interesting. With chained threading and implementantion of nvenc, swapping is roughly twice as fast (swapping only) compared to 2.0.3 on my system (i7-4770K, rtx 3060 using only 8 pci-express lanes), while it takes almost twice the time with GFPGAN compared the "old" approach. I'm curious about the difference the new system will make - parts arrived today.

But: Did all of you take the time it takes, to write the frames onto the harddrive first (2.0.3), into account? Especially with very long Videos, that took up to 20 minutes (older 2.5" s-ata ssd), which are not accounted for in the shown processing time. So of course you won't reach the same frame rates with gradio, which doesn't write all the frames first. To really compare, you have to stop the _total_ time with 2.0.3.
Also the hd's and ssd's got very warm in the process of writing all the frames first, and froze the whole system occasionally.

**Comment by eniora** [comment]
I just made a test on 3090 24GB and 1070 8GB comparing the current 2.7.3 gradio build to the old 2.0.3, they are the exact same speed on the 1070! (total time including the frame extraction for 2.0.3). What people are reporting here is weird that the gradio build is times slower than 2.0.3.
My test was on a 1 min 720p 30FPS (1727 frames) video with one face, I chose many faces/all faces on both tests with keep fps option and ran it multiple times to get an average. Didn't use enhancer. 7 threads used on 1070 and 20 threads on 3090. My tests were mainly focused on the 1070 since it seems only people with low VRAM cards are reporting these gradio slowdowns. I also tested on another 40 seconds video and same results, same speed on both.

On 1070:
2 mins 14 seconds on 2.0.3 (total time including frame extraction, swapping time was 2 mins 3 seconds)
2 mins 13 seconds on gradio 2.7.3 (total time including frame extraction, swapping time was 2 mins 5 seconds)

Here are screenshots:
[Gradio](https://i.imgur.com/FuK3gFF.jpg)
[2.0.3](https://i.imgur.com/jQ7eWRK.jpg)

On 3090 2.0.3 was ~10% faster.
I have to say though that 2.0.3 is still better at VRAM usage and clears the VRAM better than the gradio build after swapping. But what's important is that they are both the same speed for me.

Anyway looking forward to test the new thread splitting to parts update count talked about above!

**Comment by lysxelapsed** [comment]
regarding my comment that GFPGAN takes twice as long: scratch that! thanks to @phineas-pta's comment here #116, I now know why that was. Threads should be signifficantly lower when using GFPGAN. Maybe the VRAM handling with enhancers on can still be improved?

**Comment by lysxelapsed** [comment]
how's the VRAM usage? are you using an enhancer? try lowering threads further and don't forget to apply settings (happened to me a few times). or even better: start with one thread and increase one by one (apply settings and restart in between to be sure), until performance drops again.

**Comment by C0untFloyd** [comment]
Man, this stuff is really weird!
First, as other people pointed out too, v2.0.3 wasn't running faster for me than the gradio version. The frames per second display in the output isn't very accurate and just notices the timespan between progress updates. The gradio versions should in theory run faster even (when using enhancers etc.) because the gradio version doesn't do any post-processing if there is no face detected previously. **BUT** v2.0.3 always extracts all of the movie frames at the beginning and just loads them in each thread, which probably negates the speed improvement again. In theory the gradio version with 'keep frames' checked should be the fastest. 
Now back to my optimizing adventures: 
The screenshot I posted this morning, was running with every movie frame loaded into memory, which obviously won't work with bigger movie clips or less memory. So I revised the code again & again and it seemed to get even slower. Then I changed to CPU-only and it was running about 3x as fast as with CUDA-enabled. That means my improvements were working, there must be some sort of race-condition in the CUDA code or the face recognition blocks the other models. As I wrote previously, some of the roop forks went back to CPU-only. What I'm doing now is mixing it and adding preloading for slow drives.
There's now a checkbox to force the face swapping to be done on CPU and the rest will use whatever provider you selected. 
In addition a preload buffer size can be set to the number of images to be preloaded for each thread. My sweet spots are 8 threads, 16 images buffer size and force cpu turned on. This is about 4 times faster as previously. The processing time will also be output after finishing so you people don't have to guess anymore:
> Processing took 30.049463987350464 secs

**Comment by eniora** [comment]
Thanks a lot count, can't wait to test this new update! You said CPU processing is 3x times faster than CUDA and some forks are using CPU only, but I tried using the CPU as provider now and it's like 20x times slower than CUDA at face swapping (no enhancer), not sure if I am understanding you correctly here.

**Comment by C0untFloyd** [comment]
Don't worry `Force CPU` only uses the CPU for face analysis, swapping/enhancement still uses GPU (and it's toggleable).

**Comment by eniora** [comment]
Ahhh OK I see, so it's only for face analysis.
btw is it possible to implement the same mechanism 2.0.3 used to release VRAM after swapping? for example on 2.0.3 when I am swapping it uses around 6.5GB VRAM and 3.5 GB after it finishes (you can see on my screenshots above), on gradio it's using 7.8GB and 7.5GB after swapping, same settings on both. I just like how VRAM efficient 2.0.3 was, probably that's one reason why some people are having speed issues with the gradio build?

**Comment by eniora** [comment]
hmm it's much slower now after the update, tried with and without Force CPU for Face Analyzer, tried with 16 and 8 threads, tried with frame buffer size set to 0, 8, 16 and 32 and I can't get it to process more than 4 FPS. I made sure to click apply settings and restarting roop completely every time. Was 14 FPS on average before update on the same video. Now it feels like the GPU isn't being used fully and the temperature is low too.

**Comment by C0untFloyd** [comment]
Wow, that's a huge indeed! That's with keep frames unchecked, isn't it? As I wrote, it's weird because in my case it's the exact opposite, I have constantly triple the speed than before. Perhaps the 2 methods could be selectable so everybody wins...
VRAM: the only difference between those versions is the usage of classes and gradio itself. I supect it is partly because gradio is running in the browser which allocates ram just when starting. If you want to test every bit you could have your internal GPU use the browser, see if that makes a VRAM Difference.

**Comment by eniora** [comment]
Yah that's with keep frames unchecked.
Following tests were done with 20 threads, frame buffer tested on both 16-32 with the new update which didn't make a difference for me. What's weird is that VRAM usage is so low with the new update, some runs only use 8GB and it's very slow.

On 3090 (frames unchecked):

before update: [40 FPS](https://i.imgur.com/BqyHuMo.jpg)
after update: [~3 FPS](https://i.imgur.com/Q9BJLLQ.jpg)

with keep frames checked:

before update: 40 FPS
after update: 10-15 FPS

**Comment by C0untFloyd** [comment]
> before update: 40 FPS (33 seconds swapping time) after update: 33 FPS (41 seconds swapping time)

This, I don't understand even remotely. There was no change to the keep frames code and with force cpu unchecked it should be identical. I need a vacation...

**Comment by eniora** [comment]
> I need a vacation...

You deserve it after all this work 😂 I mean every PC, configuration etc. is different, it's hard to please everyone haha. But yah like you said, I think the 2 methods being selectable could be a good solution with the old method as default? (let's see what others here think about the new update and how it runs for them). Also if you want to test/debug anytime you want on my PC you can DM me on discord **enio0292** and I can give you teamviewer/anydesk access.

**Comment by eniora** [comment]
@C0untFloyd I think I discovered something. Sec I am still testing, will edit this post when I am done.

**Comment by C0untFloyd** [comment]
I did some more coding, simplified the threading and I believe it's now really testing your GPU capabilities. And _drum roll_ it's really fast on my machine even with everything being CUDA. The trick is to find your sweet spot, to have your GPU churning through without filling your VRAM too much. And sometimes less is more! As @eniora wrote, frame buffer size is tied to number of threads, so in my case my sweet spot is 4 Threads, 4 Frame Buffer Size. This means an image buffer of 4x4 =  16 Images. With that I have a constant speed of 8 fps which is awesome for my mediocre card. Be aware that this needs to be tweaked when using enhancers to avoid overfilling your VRAM. With GFPGAN my sweet spot is 2*4. I just committed the new code and need to sleep. Only 4 hours sleep for me tonite then  😭  Have fun!

**Comment by C0untFloyd** [comment]
Used my morning break to debug some more, there was a huge threading bug which corrupted the frame order. Fixed it real quick, loosing ~ 1 frame per second due to race conditions though.  As I said before 'Keep Frames' doesn't use the latest changes, it's the same as always (excluding the force cpu thing).
I have a new supect why the slowdowns are happening:
https://github.com/C0untFloyd/roop-unleashed/blob/old_deprecated/roop/core.py#L109
^ uncommented in the old tkinter branch

https://github.com/C0untFloyd/roop-unleashed/blob/main/roop/core.py#L112
^ activated

And @eniora is the one to blame because of his VRAM Complaints! 😄 
Before that activation there was no tensorflow dependancy and I didn't have this wildly varying slowdowns. The code was copied straight away from the original roop, I need to test if this is part of the solution later.

**Comment by AlonDan** [comment]
Just an idea to make things faster:
Maybe to make things a bit faster when processing is the way the good old **Windows GUI** roop unlashed was?

First Extract the whole sequence, only then do the rest (preview or render)
So it will always read from the temporary folder, once load a different video / sequence remove the first one so it won't keep leftover junk and used lots of space with unused images.

**Comment by eniora** [comment]
All good now 😁 thank you!
With the latest commit from an hour ago it's fast and good, no flickers. Testing on 1070 with 5 threads and 5 buffer size, it's as fast as 2.7.3 but with Force CPU for Face Analyzer disabled (I think it should be disabled by default after installing unleashed), when I enable it it takes twice the time to swap and process, same with my home PC which has 3090 and 5950x.
Yah sorry about the VRAM complaints, I was just comparing with the old tkinter build and thought it would be an easy fix hehe.
I am waiting to see the others who commented here and complained about the speed and how the performance is for them now after all these commits.

Now with the enhancer enabled, I am getting a ~30 seconds pause at the end of frame processing every time, like this:

![Screenshot 2023-08-17 125607](https://github.com/C0untFloyd/roop-unleashed/assets/116663473/c3859eaa-04f4-419a-bcfb-d04c5d8e1958)

It pauses for 30 seconds shortly before processing the last few frames, never had this with 2.7.3
No GPU or CPU usage I can see while it's stuck, I guess the enhanced buffered frames are being released from memory that causes the slowdown?
I am using 5 threads and 5 buffer for the above screenshot, using 2 threads and 4 buffer fixed the issue, so like you said it's 2x4 for enhancers with your 8GB card and seems like it applies to me. It's weird because with 5x5 my VRAM wasn't full, max was 7.3GB out of 8GB with no shared memory usage. Anyway I think I will be using 3x5 for everything on 1070 which is a good balance with or without enhancers and no slowdown at the end of processing.

**Comment by C0untFloyd** [comment]
> Just an idea to make things faster: Maybe to make things a bit faster when processing is the way the good old **Windows GUI** roop unlashed was?
> 
> First Extract the whole sequence, only then do the rest (preview or render) So it will always read from the temporary folder, once load a different video / sequence remove the first one so it won't keep leftover junk and used lots of space with unused images.

That's exactly what happens when checking `keep frames` 😛

> No GPU or CPU usage I can see while it's stuck, I guess the enhanced buffered frames are being released from memory that causes the slowdown?

Sort of. I couldn't debug it yet but I assume it's because at the end there is a race condition with the remaining frames needing to be written to the resulting file in the correct order. The more threads, the more images left and if there's a bunch of them the saving thread is too slow (also depending on your media speed of course). See, that's the cool thing with the new revised code. Previously while processing a video one thread was waiting for the previous to come to an end to keep the frame order intact. Now they just process as much as fast as they can and the extra saving thread cares about sorting and saving. I for one don't want to go back, even on my old laptop the whole process is much faster than previously, even comparing it to the tkinter version. Try processing a video with parts without faces and see the framerate fly into the 2-digits 🤣

**Comment by eniora** [comment]
> The more threads, the more images left and if there's a bunch of them the saving thread is too slow

Sorry to say this but can you PLEASE make a toggle in settings to disable the buffering system/recent optimizations and make it like 2.7.3? Like I said before, people have all kinds of rigs and configs so what works for me or you may not work best for them so the more options the better IMO. I am saying this because when the enhancer is enabled anything more than 3 threads causes that long pause to happen at the end and with 3 threads it's slower than on 2.7.3 where I was able to set it to 5-6 threads and processing time was ~30% faster. To be honest with you all the updates since yesterday didn't give me any speed boost compared to 2.7.3 with or without enhancer and with two computers one with 1070 and one with 3090.

> That's exactly what happens when checking keep frames

Can you also make a toggle that simulates the keep frames option and deletes them automatically after processing? (exactly like old roop) so people who have issues or slowdowns with the new gradio update for whatever reason can have flexibility with choosing what works best for them.

**Comment by C0untFloyd** [comment]
> Can you also make a toggle that simulates the keep frames option and deletes them automatically after processing? (exactly like old roop)

Done. Also I removed the supposed memory leak fix for tensorflow I'm curious if this changes anything, perhaps this makes the new method fast for you too? Committed as v2.7.6

While testing the old method again I noticed totally different speeds between runs. The first run had me swapping at a mediocre ~ 3 fps. I started over again and it was very slow at about 1.45 fps. After coding some more and doing another run I had ~ 8 fps almost constantly! This is really weird, my best guess is that VRAM is garbage collected in a lazy fashion and if it's full there is some memory swapping going on. I doubt this can be solved by code.

**Comment by eniora** [comment]
Very nice implementation of the In-Memory and Extracting frames option!

Tested the new commit on both 1070 and 3090, Force CPU for Face Analyser is still slow for me (which I have it disabled now for all my tests) and that pause at the end still happens when I am using the enhancer and even on a 3090 I have to set threads to 3 max for the pause to not happen which is very slow compared to when I set it to 16 (which causes a 20-30 seconds pause at the end 10-15 frames before the total, and that's regardless of how many buffer size I set). Looks like how early the pause happens, which is always near the end in any case, is relevant to what the Frame Buffer Size is set to.
>I assume it's because at the end there is a race condition with the remaining frames needing to be written to the resulting file in the correct order

But if that's true, why doesn't it happen when the face enhancer isn't enabled? that pause only happens if GFPGAN is enabled.
Can you please make it that if I set threads to 0 it means it's disabled completely (like 2.7.3)? If only that pause doesn't happen everything would have been perfect. 😢

**Comment by C0untFloyd** [comment]
Committed the next iteration of it, the pause should be gone. I'm curious if this makes a difference with your 3090, I noticed both methods degrade after the first run and seem to run slower. But it's not always and after the first run the degradation does never continue and the speed stays roughly the same. For me there's hardly a difference between both methods in terms of speed now. Both run best with 4-5 threads in my tests and smaller buffer size of 2-3. The buffer size isn't used with the extract frames method anyway.

**Comment by eniora** [comment]
Awesome! everything working great now, no pauses or anything. My sweet spot is 18x18 for threads and buffer on 3090 and it's now sometimes faster than 2.7.3! or at least the same speed. With extract frame method it's the same speed as well but I prefer in-memory processing anyway (my suggestion before to add the proper extract frames feature was for people who have issues with in-memory). Force CPU for Face Analyzer still much slower for me at swapping and processing (only faster at detecting the source face and target image/video).

Small suggestion: extract frames method doesn't show the fancy new total time feature :P 
This 2.7.7 update is now capable to replace 2.7.3 for me 😄 thanks a lot.

**Comment by eniora** [comment]
@C0untFloyd with one swap out of many I did I had an error with 2.7.7

>2023-08-19 03:16:25.7321029 [E:onnxruntime:Default, cuda_call.cc:116 onnxruntime::CudaCall] CUDA failure 719: unspecified launch failure ; GPU=0 ; hostname=DESKTOP-owner ; file=D:\a\_work\1\s\onnxruntime\core\providers\cuda\gpu_data_transfer.cc ; line=63 ; expr=cudaMemcpyAsync(dst_data, src_data, bytes, cudaMemcpyHostToDevice, static_cast<cudaStream_t>(stream.GetHandle()));

It happened in the middle of swapping (around 50% in) and it kept throwing this error hundreds of times in the console and I had to close it, I forgot to do control + C so I could go up and see the full error and how it started.
Anyway it only happened once and I was testing on a 9k frames video, tested again twice and it didn't happen. If it happens again I will let you know.

Here is a benchmark with 2.7.7 against 2.7.3 with a 9k frames video:

2.7.7 (16 threads x 16 buffer)
![2 7 7](https://github.com/C0untFloyd/roop-unleashed/assets/116663473/5bd6838f-c1ba-42aa-aa89-add47432bd75)

2.7.3 (20 threads)
![2 7 3](https://github.com/C0untFloyd/roop-unleashed/assets/116663473/ea782648-5dda-4b44-a2e2-40326e4bf5bb)

I would say the speed difference is in the margin of error at this point and I may need to tweak my settings further for 2.7.7 to get the best performance.

**Comment by Siraj-HM** [comment]
I tested the latest build on my 3070 with eight threads and frame buffer 4. It starts at 12fps but drops to 11s per frame after 25% processing. I tried the keep in memory option too same thing happened :( what am I doing wrong folks?

**Comment by eniora** [comment]
@Siraj-HM try with 3-4 threads, you're filling your VRAM with 8 threads on 3070

**Comment by eniora** [comment]
I just tested on a 1070 8GB, everything is working good and it's actually ~10% faster than 2.7.3 on an average benchmark I did with 5 runs, especially with enhancer. I did multiple runs on the same session and no slowdowns occurred at all. My settings were:

In-Memory processing method
Force CPU for Face Analyser disabled
4 threads with 4 buffer size

Like I said, the new 2.7.7 update (or most updates after 2.7.3) use more VRAM on the same thread count, so if you for example used 5 or 6 threads on 2.7.3 you have to use 4 threads on 2.7.7 (with 4 buffer size). Don't worry, the speed should be the same or even slightly faster with 4 threads on 2.7.7 compared to 6 threads on 2.7.3. The idea is that you don't want to fill your VRAM because if that happens roop will start using the shared memory which is hundreds of times slower than the GPU memory hence the significant slowdowns, that's why it's a good idea to start with a low thread count and start increasing until your VRAM fills then undo the last thread increase.

**Comment by AlonDan** [comment]
I just did some tests with the default 2.7.7 settings and I get so much slower results compare to what I had before (not that it was super fast)
So I tried the new feature: "Extract Frames to media" because I hope it will do what the good old Roop Unleashed GUI for windows did extract super fast, than start MUCH FASTER than anything I get in gradio with my old machine.

Unfortunately, it is still exactly the same super slow on my machine, 
I did the exact same with the old Roop Unleashed GUI and it was so much faster just like I remembered, so I guess I'll have to stick with the old version (I know it's much limited) but I have no choice as I only have:

- Intel i7 3.5Mhz 32GB RAM
- Nvidia GTX 980 4GB DDR
- runs on SSD (Windows 10)

which is not good for the latest Gradio version, it's just extremely slower to render few seconds of one video.

I guess it works great for more modern machines so at least it's going good ways with that, unless there will be some "magic" in the way it will work more like the GUI one with super fast export fast and maybe the process itself is just so much slower for other reasons I have no idea, but if some cool change in that area will happen I'll sure give it a try and let you know if it improved. 

In the meantime, please keep up the good work! ❤

**Comment by eniora** [comment]
@AlonDan can you please try on the new 2.7.7 with the following settings:

Threads 1, Buffer 1
In-Memory processing
Force CPU for Face Analyser disabled

The reason it's slow for you because your 4GB VRAM is getting full with the default settings which is 4 threads.

With only 1 thread it's still really fast for me and only slightly faster than with 4 threads, though my VRAM usage is 4.2GB so hopefully it would work for you, it's worth a try!

![Screenshot 2023-08-19 174053](https://github.com/C0untFloyd/roop-unleashed/assets/116663473/e7b70212-d0d9-4901-a4c0-165d33d2e76f)

**Comment by Darknessssenkrad** [comment]
everything seems to be fixed, I can use 1 Thread on my 3050 (laptop) and 14 frames
BUT on the Colab notebook  it's crazy
12 Threads and 14 Frames it's what I'm using on the colab I get 10-12 frames/second no enhancements

2023-08-19 16:11:50.324872: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-19 16:11:52.009750: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Using provider ['CUDAExecutionProvider'] - Device:cuda
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://45e46d4e3119fd686a.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0'}}
find model: /root/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0'}}
find model: /root/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0'}}
find model: /root/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0'}}
find model: /root/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0'}}
find model: /root/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
[ROOP.CORE] Processing video /content/roop-unleashed/temp/7d5ae92c96a09c7a03a537eb421e92c32220c31c/test.mkv
[ROOP.CORE] Creating video with 22.0 FPS...
['ffmpeg', '-hide_banner', '-hwaccel', 'auto', '-y', '-loglevel', 'error', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '854x480', '-pix_fmt', 'bgr24', '-r', '22.0', '-an', '-i', '-', '-vcodec', 'libx264', '-crf', '14', '-vf', 'colorspace=bt709:iall=bt601-6-625:fast=1', '-pix_fmt', 'yuv420p', '/content/roop-unleashed/output/test_fake.mp4']
Processing:   0% 0/3875 [00:00<?, ?frame/s]Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'CUDAExecutionProvider': {'device_id': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_alloc': '0', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'cudnn_conv1d_pad_to_nc1d': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'do_copy_in_default_stream': '1', 'enable_cuda_graph': '0', 'cudnn_conv_use_max_workspace': '1', 'tunable_op_enable': '0', 'enable_skip_layer_norm_strict_mode': '0', 'tunable_op_tuning_enable': '0'}}
inswapper-shape: [1, 3, 128, 128]
Processing:  11% 424/3875 [00:59<05:25, 10.61frame/s, memory_usage=06.44GB, execution_threads=12]

**Comment by AlonDan** [comment]
Thanks for the advice @eniora 
I just tried few tests based on your suggestion, I don't see much difference actually when I use 1 thread and 1 buffer it's slower than when I use 4 threads, at least I could get almost 3.x fps, now I get 1.x

I also did some tests with different numbers such as: 
Buffer: 1-2 
and same with Thread: 1, 2 and 3 (4 was the default)

I don't think it likes old machines such as my GPU, while I get something like 8-9 fps in the good old Roop Unleashed GUI... I know, I'm loosing the good cool features but it's so much faster. 1.x - 3.x is very slow.

I hope it will be improved in the future, but I'm not counting on it because my hardware is ancient tech.

Anyway, thanks for trying to help I appreciate it ❤

![cmd_2023-08-19_19-44-25](https://github.com/C0untFloyd/roop-unleashed/assets/21152334/02ed330e-8995-425e-be42-aee19fdb0fa4)

**Comment by eniora** [comment]
@AlonDan You're welcome! Yah I think your GPU doesn't work well with Gradio for whatever reason. Do you remember your VRAM usage while it was swapping using 1 thread? I wonder if it was more than 4GB and if it was using the shared memory at this point.🤔

**Comment by AlonDan** [comment]
> 

VRAM was about It was around 3.4 - 3.9 sometimes 4

I'll keep my eyes on Roop Unleashed Gradio, the community is sure awesome.
I wish the GUI version could also continue but oh well... Gradio is more efficient probably

**Comment by eniora** [comment]
Hm I see, then I am pretty sure it's a VRAM issue and roop goes crazy and very slow when it starts using shared memory after dedicated GPU memory gets full, I just simulated it as a test by using 8 threads on my 1070 and it started swapping at less than 1FPS since my VRAM got full and then it switched to shared memory, like this:

![Screenshot 2023-08-19 210444](https://github.com/C0untFloyd/roop-unleashed/assets/116663473/967dddaf-4c36-436c-a7cc-262e99c0a69a)

I admit that the old unleashed (with tkinter UI) was more efficient with VRAM, with gradio you can workaround it with GPUs with 6GB by using 1 or 2 threads but for 4GB looks like it's not possible as there are some models that needs to be loaded into VRAM regardless of the used thread number 😢.
Anyway I believe the reason count went with gradio is because tkinter is limited and didn't allow him to add features seamlessly like it's the case with gradio.

**Comment by AlonDan** [comment]
It could be, but it's starting slow and not like in the GUI version that it started fast and when it gots to it's limit only then it got slower and by just a bit in most cases.

In my Gradio tests (latest version) it just steady slow from frame 1... nothing much to improve from the start if I compare to the GUI version in this case at least, but I think you're right maybe it's because it's more aggressive on VRAM, after all it's browser based which already use more VRAM without the extra actual process.

**Comment by eniora** [comment]
Yah that's weird, hopefully count can somehow manage to do a fix for low VRAM cards.
Anyway even the original roop is now moving to gradio, it's now called and renaming to facefusion 😄 
The full story behind the rename and why they're doing it can be found on its main page [here](https://github.com/facefusion/facefusion) which is interesting. I am not sure if the old original roop repo will be removed though.

**Comment by C0untFloyd** [comment]
Wow those are some news...I knew there was something going on when the next branch secretly disappeared.
Sounds like the original repo will be removed, perhaps we should rename _The App Formerly Known As Roop Unleashed_ too?
@AlonDan And it even slows down so bad with the old 'Extract frames' method? On my old laptop with 6 Gb VRAM I can have that running with 4 threads with ok speed.
What most people seem to get wrong (because it changed quite a bit during the updates) is the frame buffer size. I'm not preloading images anymore, this is just a limit if your GPU is processing slower than your hd loads the frames). I dont think that with a slow to intermediate system you would need to set this to a higher value than 4, even this is probably overkill. Having this at a lower number can even relax the thread blocking because it's not pushing images so fast into the processing buffer. If you have a fast GPU you should instead increase the number of threads. There's also a huge difference between the 2 processing methods. The extract frames method can work with a lot more threads as there is no bottleneck in waiting for the correct frame order. Perhaps I should make that one the default as it is a lot more robust. One of these days I need to start on the wiki.

**Comment by eniora** [comment]
>Wow those are some news...I knew there was something going on when the next branch secretly disappeared.
Sounds like the original repo will be removed, perhaps we should rename The App Formerly Known As Roop Unleashed too?

Yah and now for some reason also rope disappeared and the github page can't be found ([404](https://github.com/Hillobar/Rope)) 😕 not sure what's going on xD
Anyway yah I think renaming unleashed would be the right thing to do but maybe first let's see what happens to the original repo.

**Comment by C0untFloyd** [comment]
Cease and desist incoming, better rename to nopr0nhere_no_sir.exe

**Comment by eniora** [comment]
@C0untFloyd I know this isn't the topic to ask for this but I don't want to make an issue topic for this small request xD after the new Show Progress in UI/Stop processing update (which is really nice!), now it doesn't show anything in the console while it's processing including the FPS counter which is important I would say. :P Maybe you can add the FPS counter in the UI?

**Comment by AlonDan** [comment]
> @AlonDan And it even slows down so bad with the old 'Extract frames' method?

Yes, that was weird as well for me I get the same with or without extract frames option.
In the old GUI it was very visual as well to see: "Hey! I'm extracting first... let me finish" which was usually VERY FAST by itself of course, only then starting the process.

I don't know exactly if something is wrong at the moment with the "Extract Frames" or maybe there is just no indication if it does extract first (nothing on the UI or the console to tell me) it when I start the process.... there is no sign of extracting, it just start processing and I get the same VERY LOW speed.

That's why there is a huge difference on speed that I notice from the GUI to the Gradio one at the moment at least, as I said maybe it's something you'll be able to solve or improve and it will be closer to what the GUI did, that will be great.

**Comment by C0untFloyd** [comment]
@eniora I just KNEW you would complain 😃 

I didn't remove it, it's an issue with gradio preventing the output -> https://github.com/gradio-app/gradio/issues/5272

> I don't know exactly if something is wrong at the moment with the "Extract Frames" or maybe there is just no indication if it does extract first (nothing on the UI or the console to tell me) it when I start the process.... there is no sign of extracting

But there should be -> `update_status('Extracting frames...')`
This line should be in the terminal and in addition with the latest version the gui shows a timed infobox at the top, right side.
Can it be that you somehow only ever used the In-Memory method without knowing? Perhaps I should output the method used...

**Comment by eniora** [comment]
>I just KNEW you would complain 😃

You know me by now haha 😁 ok thanks! didn't know it's an issue with gradio and thought you overlooked it or something.

>This line should be in the terminal

Ya it's there:

![Screenshot 2023-08-20 122852](https://github.com/C0untFloyd/roop-unleashed/assets/116663473/e713ab56-7d16-4415-9d20-fee704ab2855)

**Comment by lysxelapsed** [comment]
No it's not. Even my old 1660 Super (6GB) worked with gradio. i7-4770k with 3060 (12GB) now. 4 threads, 4 frames buffer size (no enhancement). About 90% GPU utilization, VRAM at around 9GB. With GFPGAN I'm reducing to 2 threads, 2 frames buffer size, both VRAM and GPU around 90%. But it depends on other factors too, your target material for example. I'm re-encoding every target video to 1280x720 with my old rig first, since it's a lot faster for swapping. 1 Thread should not use up your whole 8GB's of VRAM though, not even with GFPGAN.
Gradio version is up to twice as fast for me - both were tested with the same videos.

To everyone having out of memory issues, I recommend starting with 1 thread and go from there. If nothing helps, do a _clean_ re-install of everything including cuda, and don't update the display driver afterwards. Cuda installation comes with the one you need for the specific cuda release.

**Comment by C0untFloyd** [comment]
For me #203 released today is the fastest ever, only using 2 threads all the time. With 8 Gb or less you shouldn't use more threads.

**Comment by Sevensleeper81** [comment]
Hello! 

I have got AMD Ryzen 9 7945HX Laptop CPU and 4060RTX 8Gb VGA. 
I would like to know Number of Threads. 
What number is perfect for my Laptop? Thanks

**Comment by lysxelapsed** [comment]
> Hello!
> 
> I have got AMD Ryzen 9 7945HX Laptop CPU and 4060RTX 8Gb VGA. I would like to know Number of Threads. What number is perfect for my Laptop? Thanks

The answer's right above your post: Not more than 2.
