### ISSUE TITLE
Huge VRAM usage with the new GFPGAN onnx threading method Edit: and the quality is bad compared to the old method (see comparison at the end of the post)

### ISSUE THREAD

**Issue by eniora** [C0untFloyd/roop-unleashed#144]
First of all, thanks for the continued innovation, seriously!

Anyway I got huge VRAM usage even with only 10-12 threads on a 3090 with GFPGAN on 2.7.9 build, it always fills up the VRAM and starts using the shared memory and it becomes too slow. I even tried on only one face on a short, low resolution video. Up to 8 threads it uses 19GB VRAM, so perhaps you can make a separate threads count slider for GFPGAN/enhancer? GFPGAN is indeed faster now than the older builds with 8 threads so it would be so convenient to have a separate thread count setting for it.

![Screenshot 2023-08-22 044721](https://github.com/C0untFloyd/roop-unleashed/assets/116663473/2afa1bd6-12c9-4dc7-974f-39347acfa8c6)

**Edit:** On 1070 it's much less aggressive, instead of 4 threads which I used on 2.7.8, I now have to go down to 3 threads for the enhancer, usage is around 7.4GB. And man it's much faster! Based on my calculations it's around 6-8FPS now (instead of 1-2 FPS). Please get back the FPS counter in the console like before so we can compare the speed.😀If I understood correctly you can't yet implement it in the gradio UI after the "progress in the UI" update because of some gradio limitation but you can get it back to the console right?

Just made a comparison because the new model is doing weird artifacts to the swapped images/videos so I thought why not do a direct comparison with the old GFPGAN method and to my surprise the new model quality is bad, especially from side face angles but can also be noticed on front face views in some frames, here's a quick comparison:

![Untitled](https://github.com/C0untFloyd/roop-unleashed/assets/116663473/1b45a8cd-3190-46b0-a7ea-a292b7afeb34)

**Comment by lysxelapsed** [comment]
Thanks for the newest update! GFPGAN to onnx makes enhancement finally usable for my "dinosaur-rig" ;-) - still haven't assembled the new rig due to health issues caused by the current heatwave. Speeds are insane compared to before.
@eniora I had to drastically reduce the threads with GFPGAN even before the update. After the latest update I had to reduce further. I'm on 2 Threads, 2 Frames buffer size now, both GPU and VRAM utilization are around 90%. Works like a charm and no OOM-errors even after batch-processing 5 videos. i7-4770k with RTX 3060 (12GB)
FPS display back to console would be nice, yes. Not really sure if the gradio issue affects that, too.

**Comment by C0untFloyd** [comment]
> the new model quality is bad, especially from side face angles

If you look closely you can see the model is doing the same, but the old one applied extra blur to the frame and its edges. I'm currently converting codeformer (which I prefer over GFPGAN) and there it is even more important to do some post-processing to the enhanced. Very likely the code from this experiment can be used for GFPGAN too. I'm tempted to use some stuff from Rope too, since it has been abandonded.

**Comment by eniora** [comment]
> If you look closely you can see the model is doing the same, but the old one applied extra blur to the frame and its edges.

Hmm fair enough but if you look closely you can see that the teeth on the old model from the second example is better than on the new model, and that has nothing to do with softening/blurring the frame. The issue appears worse on videos too, it looks like artifacts because it's more apparent on side views and less on front views so the overall video look is weird.

**Comment by eniora** [comment]
@C0untFloyd It's really not about sharpening, the new GFPGAN model is broken, here see for yourself, most face features are gone with the new model. Just tested again on v2.8.2:

![Untitled](https://github.com/C0untFloyd/roop-unleashed/assets/116663473/ee7596e4-9b2f-482a-a244-38ddbedf91b6)

I know you said you're currently working on converting codeformer model and without artifacts like this, and I really appreciate the speed boost with the new GFPGAN model but it's just not usable in its current state IMO. Is it possible to revert to the old GFPGAN model meanwhile until you figure out a fix for the bad quality/artifacts? you can't imagine how bad it looks on videos especially when face angles change, you can easily test that.

Cheers! oh and it's been a while since I last annoyed you. I am back 😈 ❤️

**Comment by C0untFloyd** [comment]
It took some time but should be resolved by #203

**Comment by eniora** [comment]
Thanks. Haven't had the chance to test all these new updates yet. Will test tomorrow.😃

**Comment by C0untFloyd** [comment]
> Haven't had the chance to test all these new updates yet. 

That's because you were flirting with face fusion again!

![attached](https://github.com/C0untFloyd/roop-unleashed/assets/131583554/3f5df848-093c-41cd-94f1-3b21e586ef26)

**Comment by eniora** [comment]
OK just tested and looks like it's much better now. Artifacts with GFPGAN still exist to an extent but are way less and I can live with that. Using 2 threads on a 1070 uses about 6.5GB VRAM.

>That's` because you were flirting with face fusion again!

Not sure what do you mean here xD I don't even have face fusion installed lol (I don't like the interface at all anyway)
