### ISSUE TITLE
Warning ffmpeg is not installed! No video processing possible.

### ISSUE THREAD

**Issue by kacperionek** [C0untFloyd/roop-unleashed#511]
Warning
ffmpeg is not installed! No video processing possible.

**Comment by CassySpencer** [comment]
@C0untFloyd that was not very useful. There are many of us that are new to this and what you provided just did not help. If you can't help, go away but if you have the capability, be a decent human being and provide valuable assistance. What do you provide was 100% useless!

Just do a YouTube video of someone installing this on a Mac and post that.

**Comment by kutasos** [comment]
<img width="366" alt="Zrzut ekranu 2024-04-20 164808" src="https://github.com/C0untFloyd/roop-unleashed/assets/52929620/f3be6ed5-52a4-4e57-a29f-c4521797cf8a">

Nothing was working for me but I have found one solution that can be helpful also for you.

In system environment find ROOP Path and paste your ffmpeg files in that location.

**Comment by MateuszKudelko** [comment]
Możesz podpowiedzieć jak to zrobić ?

**Comment by dasmole0** [comment]
In the directory "\roop-unleashed-main\installer\installer_files" - I just renamed the folder "ffmpeg-2023-06-21-git-1bcb8a7338-essentials_build" to "ffmpeg" and that should fix it (that whole folder is extracted from the ffmpeg.zip)

**Comment by spudnick1UK** [comment]
> In the directory "\roop-unleashed-main\installer\installer_files" - I just renamed the folder "ffmpeg-2023-06-21-git-1bcb8a7338-essentials_build" to "ffmpeg" and that should fix it (that whole folder is extracted from the ffmpeg.zip)

I did the same and it worked fine for a few days then got the same problem so i deleted all and did a new install and changed the FFMPEG and all works ok atm

**Comment by JimmyDev1** [comment]
> In the directory "\roop-unleashed-main\installer\installer_files" - I just renamed the folder "ffmpeg-2023-06-21-git-1bcb8a7338-essentials_build" to "ffmpeg" and that should fix it (that whole folder is extracted from the ffmpeg.zip)

this is it this is the one this is the greatest github comment help ever!

**Comment by spudnick1UK** [comment]
To resolve this issue permanently it is best to install to window
Even changing file name after a while it still gets the issue

**Comment by yannos80** [comment]
renommer le dossier "ffmpeg-2023-06-21-git-1bcb8a7338-essentials_build" en "ffmpeg

**Comment by trinhxuankhanh** [comment]
> In the directory "\roop-unleashed-main\installer\installer_files" - I just renamed the folder "ffmpeg-2023-06-21-git-1bcb8a7338-essentials_build" to "ffmpeg" and that should fix it (that whole folder is extracted from the ffmpeg.zip)

Thanks bro, I work for me <3
