### ISSUE TITLE
Post-processing error

### ISSUE THREAD

**Issue by Tnev44** [C0untFloyd/roop-unleashed#800]
**Describe the bug**

**To Reproduce**
1. Add input and target face image
2. Select post-processing
3. Swap faces
4.  Gives this error message OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:674: error: (-5:Bad argument) When the input arrays in add/subtract/multiply/divide functions have different types, the output array type must be explicitly specified in function 'cv::arithm_op'

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [x] Windows 
- [ ] Mac

Are you using a GPU?
- [ ] No. CPU FTW
- [x] NVIDIA
- [ ] AMD
- [ ] Intel
- [ ] Mac

**Which version of roop unleashed are you using?** 4.1.0

**Screenshots**

**Comment by CryptoMeoww** [comment]
Same Error and the same configuration 
<img width="660" alt="ScreenShot_20240715032349" src="https://github.com/user-attachments/assets/b4be5676-997f-4cf6-8e31-9137c292a540">

**Comment by Tnev44** [comment]
> Same Error and the same configuration <img alt="ScreenShot_20240715032349" width="660" src="https://private-user-images.githubusercontent.com/175566612/348572334-b4be5676-997f-4cf6-8e31-9137c292a540.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5OTQ1NDUsIm5iZiI6MTcyMDk5NDI0NSwicGF0aCI6Ii8xNzU1NjY2MTIvMzQ4NTcyMzM0LWI0YmU1Njc2LTk5N2YtNGNmNi04ZTMxLTkxMzdjMjkyYTU0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQyMTU3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmU5OTZhOTcyN2E1MDJiYzk3NTY4ZDI5ZjdiNWQ4MmZkNjk3NDkwZDNkZTc5MmYyOThhOTI4OGViYjE1YzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CCwobWZ6jRDluR1PLONXOvOjtYEIGg-HBtK0q5IeGCo">

It just began happening today. I gotta go to work but any help would be appreciated.

**Comment by Alexisback** [comment]
Same error, with Subsample upscale to 512px and GFPGAN active, 

![sshot-1](https://github.com/user-attachments/assets/7836e02c-36d1-4a14-a11f-a4dc5e26f7b3)


![sshot-2](https://github.com/user-attachments/assets/81ad5bad-37a3-4b3e-830f-bb93ec983a20)


with alone Subsample upscale to 512px no errors

![sshot-3](https://github.com/user-attachments/assets/3f0f656d-26a3-478b-9bef-f98acfd59358)

**Comment by Tnev44** [comment]
> Same error, with Subsample upscale to 512px and GFPGAN active,
> 
> ![sshot-1](https://private-user-images.githubusercontent.com/18039740/348572718-7836e02c-36d1-4a14-a11f-a4dc5e26f7b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5OTU4OTksIm5iZiI6MTcyMDk5NTU5OSwicGF0aCI6Ii8xODAzOTc0MC8zNDg1NzI3MTgtNzgzNmUwMmMtMzZkMS00YTE0LWExMWYtYTRkYzVlMjZmN2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDIyMTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YTYyMTgwNmUyYTU3M2IxZTg1MmEwYTk1YzcwMGQzNWUzM2FhNDRkMzZhNmYwNzQ3M2ZmZmFhOWQ0ZTNkODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9viXWi9hY8DSUv1ZhqDrmPj23tR5vRNo7iwNV2y9IHg)
> 
> ![sshot-2](https://private-user-images.githubusercontent.com/18039740/348572728-81ad5bad-37a3-4b3e-830f-bb93ec983a20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5OTU4OTksIm5iZiI6MTcyMDk5NTU5OSwicGF0aCI6Ii8xODAzOTc0MC8zNDg1NzI3MjgtODFhZDViYWQtMzdhMy00YjNlLTgzMGYtYmI5M2VjOTgzYTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDIyMTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NzkzMTJhNGE2NjVjNDJjMzQyZDA4NDEyMWIyMmE0OTkzYjA4ZjczNGQxYjhhZjc3NzFhYjM3OTM0ZWQyMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hKUewt6h-6FpzQ4jY1Y1_4vdMzqbmydTbj0_uMoALlw)
> 
> with alone Subsample upscale to 512px no errors
> 
> ![sshot-3](https://private-user-images.githubusercontent.com/18039740/348572800-3f0f656d-26a3-478b-9bef-f98acfd59358.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5OTU4OTksIm5iZiI6MTcyMDk5NTU5OSwicGF0aCI6Ii8xODAzOTc0MC8zNDg1NzI4MDAtM2YwZjY1NmQtMjZhMy00NzhiLTliZWYtZjk4YWNmZDU5MzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDIyMTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZTIzYzIxNjcyNzhlZGNkMjE3MDk4MDBhNmVmNWFlNjYyZjllNTAyNDNjMTA5MzRiZmJlZjYwYTAxYWNiZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DB0TcgWjBIPaj4tZPsrJI7uBMJQ9PUHh_SNNfhU5PYM)

That's what I noticed; without post processing it works but its low quality.

**Comment by Attritionist** [comment]
Same issue on here is it only on the latest new version?

**Comment by oly1kenobi** [comment]
Same issues here... since update today

**Comment by batheinherchest** [comment]
any fix for this? having the same issue.

**Comment by kumarvivek1752** [comment]
same issue
![image](https://github.com/user-attachments/assets/94fd994b-c982-44d4-bc24-9094fbb4a125)

**Comment by CKVNZ** [comment]
I think many people are having this error. Anyone has solution?

**Comment by testygit01** [comment]
Getting the same error.

**Comment by zeki0485** [comment]
target file:
roop-unleashed4.1\roop\ProcessMgr.py

Find the following lines:
if upsk_face is not fake_face:
fake_face = cv2.warpAffine(fake_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
paste_face = cv2.addWeighted(paste_face, self.options.blend_ratio, fake_face, 1.0 - self.options.blend_ratio, 0)

and replace it with:
if upsk_face is not fake_face:
fake_face = cv2.warpAffine(fake_face, IM, (target_img.shape[1], target_img.shape[0]), borderMode=cv2.BORDER_REPLICATE)
# Ensure both arrays have the same data type
paste_face = paste_face.astype(np.float32)
fake_face = fake_face.astype(np.float32)
paste_face = cv2.addWeighted(paste_face, self.options.blend_ratio, fake_face, 1.0 - self.options.blend_ratio, 0)

**Comment by sasaxkev** [comment]
Select "none" for post-processing, works for now

**Comment by Attritionist** [comment]
Just went back to the old version and it's working fine will wait for a patch

**Comment by kumarvivek1752** [comment]
@Attritionist how to rollback to  previous version

**Comment by Attritionist** [comment]
> @Attritionist how to rollback to previous version

Just download the source file for an older version and then run the run file and say no to check updates

**Comment by C0untFloyd** [comment]
Fixed

**Comment by MarcosdrVinicios** [comment]
Hello I'm getting the same issue on the release v4.1.1

**Comment by nightwatcher26** [comment]
I was having the same issue, git pull claimed the clone was up to date. I restarted windows_run.bat and selected 'y' at the 'check for updates?' prompt. Now the post-processing bug is gone for me. Thanks @C0untFloyd for the updates!

**Comment by akbaryunal** [comment]
i still got the issue... tried with the older version too but still have the problem
